name: Kerala Gold Rate Tracker - Configurable with Caching

on:
  schedule:
    # MORNING RUSH: Every 15 minutes during AKGSMA rate setting (9-11 AM IST)
    - cron: '30,45 3 * * *'      # 9:00, 9:15 AM IST
    - cron: '0,15,30,45 4 * * *'  # 9:30, 9:45, 10:00, 10:15 AM IST
    - cron: '0,15,30 5 * * *'     # 10:30, 10:45, 11:00 AM IST
    
    # MARKET HOURS: Every 30 minutes during active trading (11 AM - 6 PM IST)
    - cron: '30 5-12 * * *'       # Every hour at :30
    - cron: '0 6-12 * * *'        # Every hour at :00
    
    # EVENING RUSH: Every 15 minutes during evening updates (6-7 PM IST)
    - cron: '30,45 12 * * *'      # 6:00, 6:15 PM IST
    - cron: '0,15,30 13 * * *'    # 6:30, 6:45, 7:00 PM IST
    
    # OFF HOURS: Every 3 hours during low activity
    - cron: '30 15,18,21,0 * * *' # 9:00 PM, 12:00 AM, 3:00 AM, 6:00 AM IST
    
    # WEEKEND: Reduced frequency
    - cron: '0 2,6,10,14,18,22 * * 0,6'  # Every 4 hours on Sat/Sun
  
  workflow_dispatch: # Manual trigger

permissions:
  contents: write

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python with caching
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
        
    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@master
      
    - name: Run configurable Kerala scraper
      timeout-minutes: 6
      run: python scrape_with_notifications.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        
    - name: Generate API and website
      run: python generate_api_site.py
        
    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v4
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./docs
    #     force_orphan: true
        
    - name: Commit results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if ! git diff --staged --quiet; then
          git commit -m "Kerala update: $(date '+%Y-%m-%d %H:%M UTC') - $(TZ='Asia/Kolkata' date '+%I:%M %p IST')"
          git push
        fi